#!/bin/bash
# Local Supabase bootstrap for SnapFlow preprod testing.
#
# Run from Front-Snap:
#   ./scripts/local-supabase-preprod.sh --clean --seed-random-admin
#
# Keep this terminal open: the script ends by serving Supabase Edge Functions.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$FRONT_DIR/.." && pwd)"
V3_DIR="$ROOT_DIR/V3-Microservices"

SUPABASE_ENV_FILE="$FRONT_DIR/supabase/.env.local"
V3_ENV_FILE="$V3_DIR/.env.local"
SCANNER_BASE_URL="${SCANNER_BASE_URL:-http://host.docker.internal:8080}"
DB_PASS="${DB_PASS:-snapflow}"
DEFAULT_REDMINE_BASE_URL="https://maintenance.medianet.tn"

CLEAN=false
SEED_RANDOM_ADMIN=false

usage() {
  cat <<'EOF'
Usage: ./scripts/local-supabase-preprod.sh [--clean] [--seed-random-admin]

Options:
  --clean              Stop old SnapFlow stacks and wipe all local Supabase data.
  --seed-random-admin  Create a random confirmed local admin after migrations.
  -h, --help           Show this help.

Environment overrides:
  SCANNER_BASE_URL     Defaults to http://host.docker.internal:8080.
  DB_PASS              Defaults to snapflow for V3 local preprod Postgres.
  REDMINE_BASE_URL     Defaults to https://maintenance.medianet.tn.
  REDMINE_API_KEY      Admin API key used by local Redmine Edge Functions.
  REDMINE_LOGIN_RATE_LIMIT_SALT
                      Local-only salt for Redmine login rate-limit hashes.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --clean)
      CLEAN=true
      ;;
    --seed-random-admin)
      SEED_RANDOM_ADMIN=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
done

cd "$FRONT_DIR"

read_env_value() {
  local key="$1"
  shift

  local file line value
  for file in "$@"; do
    if [ ! -f "$file" ]; then
      continue
    fi

    line="$(grep -E "^${key}=" "$file" | tail -n 1 || true)"
    if [ -z "$line" ]; then
      continue
    fi

    value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    printf '%s' "$value"
    return 0
  done

  return 0
}

REDMINE_BASE_URL="${REDMINE_BASE_URL:-$(read_env_value REDMINE_BASE_URL "$SUPABASE_ENV_FILE" "$V3_ENV_FILE" "$FRONT_DIR/.env" "$V3_DIR/.env.preprod")}"
REDMINE_BASE_URL="${REDMINE_BASE_URL:-$DEFAULT_REDMINE_BASE_URL}"
REDMINE_API_KEY="${REDMINE_API_KEY:-$(read_env_value REDMINE_API_KEY "$SUPABASE_ENV_FILE" "$V3_ENV_FILE" "$FRONT_DIR/.env" "$V3_DIR/.env.preprod")}"
REDMINE_LOGIN_RATE_LIMIT_SALT="${REDMINE_LOGIN_RATE_LIMIT_SALT:-$(read_env_value REDMINE_LOGIN_RATE_LIMIT_SALT "$SUPABASE_ENV_FILE" "$V3_ENV_FILE" "$FRONT_DIR/.env" "$V3_DIR/.env.preprod")}"
REDMINE_LOGIN_RATE_LIMIT_SALT="${REDMINE_LOGIN_RATE_LIMIT_SALT:-snapflow-local-redmine-login}"

get_status_var() {
  local key="$1"
  local line value
  line="$(printf '%s\n' "$SUPABASE_STATUS_ENV" | grep -E "^${key}=" | tail -n 1 || true)"
  value="${line#*=}"
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  printf '%s' "$value"
}

require_value() {
  local name="$1"
  local value="$2"
  if [ -z "$value" ]; then
    echo "Could not read $name from local Supabase status." >&2
    echo "Run 'npx supabase status -o env' from Front-Snap to inspect the local CLI output." >&2
    exit 1
  fi
}

wait_for_supabase_status() {
  local attempt output last_line

  for attempt in {1..30}; do
    if output="$(npx supabase status -o env 2>&1)"; then
      SUPABASE_STATUS_ENV="$output"
      return 0
    fi

    last_line="$(printf '%s\n' "$output" | tail -n 1)"
    echo "Supabase status not ready ($attempt/30): $last_line"
    sleep 3
  done

  echo "Supabase did not become ready after waiting." >&2
  printf '%s\n' "$output" >&2
  return 1
}

reset_local_database() {
  if npx supabase db reset --local --yes; then
    return 0
  fi

  echo "Supabase db reset returned a non-zero status after migrations."
  echo "This can happen on Windows when the CLI receives a transient 502 while containers restart."
  echo "Checking whether local Supabase is healthy before continuing..."
  wait_for_supabase_status
}

write_env_files() {
  local api_url="$1"
  local anon_key="$2"
  local service_role_key="$3"

  mkdir -p "$FRONT_DIR/supabase"

  umask 077

  cat > "$V3_ENV_FILE" <<EOF
# Generated by Front-Snap/scripts/local-supabase-preprod.sh
# Used by: cd V3-Microservices && ./run-all.sh --local

DB_PASS=$DB_PASS
VITE_SUPABASE_URL=$api_url
VITE_SUPABASE_PUBLISHABLE_KEY=$anon_key
REDMINE_BASE_URL=$REDMINE_BASE_URL
REDMINE_API_KEY=$REDMINE_API_KEY
REDMINE_LOGIN_RATE_LIMIT_SALT=$REDMINE_LOGIN_RATE_LIMIT_SALT
EOF

  cat > "$SUPABASE_ENV_FILE" <<EOF
# Generated by Front-Snap/scripts/local-supabase-preprod.sh
# Used by: npx supabase functions serve --env-file supabase/.env.local --no-verify-jwt

SUPABASE_URL=$api_url
SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
SCANNER_BASE_URL=$SCANNER_BASE_URL
AUDIT_API_URL=$SCANNER_BASE_URL
REDMINE_BASE_URL=$REDMINE_BASE_URL
REDMINE_API_KEY=$REDMINE_API_KEY
REDMINE_LOGIN_RATE_LIMIT_SALT=$REDMINE_LOGIN_RATE_LIMIT_SALT
EOF
}

cleanup_environment() {
  echo "=== 0/6 Cleaning old local environment ==="
  echo "Stopping V3 default stack and removing its volumes..."
  (
    cd "$V3_DIR"
    docker compose -f docker-compose.yml down --volumes --remove-orphans
  )

  echo "Stopping local preprod stack and removing its volumes..."
  (
    cd "$V3_DIR"
    docker compose -p snapflow-local-preprod -f docker-compose.preprod.yml down --volumes --remove-orphans
  )

  echo "Stopping all local Supabase instances and deleting backups/volumes..."
  npx supabase stop --all --no-backup --yes

  echo "Removing stale Supabase volumes by prefix..."
  while IFS= read -r volume_name; do
    case "$volume_name" in
      supabase_db_*|supabase_storage_*|supabase_edge_runtime_*)
        docker volume rm "$volume_name" >/dev/null || true
        echo "Removed volume: $volume_name"
        ;;
    esac
  done < <(docker volume ls --format '{{.Name}}')
}

seed_random_admin() {
  local api_url="$1"
  local service_role_key="$2"

  echo "=== 5/6 Seeding random local admin ==="
  echo "Running: node ./scripts/seed-local-admin.mjs"
  echo "Target : $api_url"
  if SUPABASE_URL="$api_url" \
    SUPABASE_SERVICE_ROLE_KEY="$service_role_key" \
    REDMINE_BASE_URL="$REDMINE_BASE_URL" \
    REDMINE_API_KEY="$REDMINE_API_KEY" \
    REDMINE_LOGIN_RATE_LIMIT_SALT="$REDMINE_LOGIN_RATE_LIMIT_SALT" \
    node "./scripts/seed-local-admin.mjs"; then
    return 0
  fi

  echo ""
  echo "Random admin seed failed, but local Supabase is already running."
  echo "Continuing to serve Edge Functions."
  echo "To retry the seed manually from Front-Snap:"
  echo "  SUPABASE_URL=\"$api_url\" SUPABASE_SERVICE_ROLE_KEY=\"<service-role-key>\" node ./scripts/seed-local-admin.mjs"
}

if [ "$CLEAN" = true ]; then
  cleanup_environment
fi

echo "=== 1/6 Starting local Supabase ==="
npx supabase start --yes

echo "=== 2/6 Applying local migrations ==="
reset_local_database

echo "=== 3/6 Reading local Supabase credentials ==="
wait_for_supabase_status

SUPABASE_API_URL="$(get_status_var API_URL)"
if [ -z "$SUPABASE_API_URL" ]; then
  SUPABASE_API_URL="$(get_status_var SUPABASE_URL)"
fi
SUPABASE_ANON_KEY_VALUE="$(get_status_var ANON_KEY)"
SUPABASE_SERVICE_ROLE_KEY_VALUE="$(get_status_var SERVICE_ROLE_KEY)"

require_value "API_URL" "$SUPABASE_API_URL"
require_value "ANON_KEY" "$SUPABASE_ANON_KEY_VALUE"
require_value "SERVICE_ROLE_KEY" "$SUPABASE_SERVICE_ROLE_KEY_VALUE"

echo "=== 4/6 Writing local env files ==="
write_env_files "$SUPABASE_API_URL" "$SUPABASE_ANON_KEY_VALUE" "$SUPABASE_SERVICE_ROLE_KEY_VALUE"
echo "Wrote: $V3_ENV_FILE"
echo "Wrote: $SUPABASE_ENV_FILE"
echo "Redmine base URL: $REDMINE_BASE_URL"
if [ -n "$REDMINE_API_KEY" ]; then
  echo "Redmine admin API key: configured"
else
  echo "Redmine admin API key: missing (set REDMINE_API_KEY before running this script)"
fi
echo ""

if [ "$SEED_RANDOM_ADMIN" = true ]; then
  seed_random_admin "$SUPABASE_API_URL" "$SUPABASE_SERVICE_ROLE_KEY_VALUE"
  echo ""
else
  echo "Random admin seed skipped. Add --seed-random-admin to generate local login credentials."
  echo ""
fi

echo "Next terminal:"
echo "  cd ../V3-Microservices && ./run-all.sh --local"
echo ""
echo "=== 6/6 Serving Supabase Edge Functions ==="
npx supabase functions serve --env-file supabase/.env.local --no-verify-jwt
