apiVersion: v1
kind: Service
metadata:
  name: v3-nlp-worker
  namespace: snapflow-prod
  labels:
    app: v3-nlp-worker
spec:
  selector:
    app: v3-nlp-worker
  ports:
  - name: placeholder
    port: 8000
    targetPort: 8000
