apiVersion: v1
kind: Service
metadata:
  name: v3-scanner-go
  namespace: snapflow-prod
  labels:
    app: v3-scanner-go
spec:
  selector:
    app: v3-scanner-go
  ports:
  - name: http
    port: 8081
    targetPort: 8081
