apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snapflow-redis
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [snapflow-infra]
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snapflow-postgres
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [snapflow-infra]
  selector:
    matchLabels:
      app: postgres
  endpoints:
  - port: metrics
    interval: 30s
