apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: snapflow-infra
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  - port: 9187
    targetPort: 9187
    name: metrics
