apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: snapflow-infra
  labels:
    app: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
  - port: 5432
    targetPort: 5432
    name: pgbouncer
