ServerRoot "/usr/local/apache2"
Listen 80
ServerName localhost
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule headers_module modules/mod_headers.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
User daemon
Group daemon
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common
TypesConfig conf/mime.types
DocumentRoot /usr/local/apache2/htdocs
<VirtualHost *:80>
    ProxyRequests Off
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "http"
    SetEnvIf Request_URI "^/\.well-known/acme-challenge/" no-proxy=1
    Alias /.well-known/acme-challenge/ /acme/
    <Directory /acme>
        Require all granted
    </Directory>
    <Location /functions/v1/seed-users>
        Require all denied
    </Location>
    ProxyPass /auth/v1/ http://supabase-gateway:8000/auth/v1/
    ProxyPassReverse /auth/v1/ http://supabase-gateway:8000/auth/v1/
    ProxyPass /rest/v1/ http://supabase-gateway:8000/rest/v1/
    ProxyPassReverse /rest/v1/ http://supabase-gateway:8000/rest/v1/
    ProxyPass /functions/v1/ http://supabase-gateway:8000/functions/v1/
    ProxyPassReverse /functions/v1/ http://supabase-gateway:8000/functions/v1/
    ProxyPass /storage/v1/ http://supabase-gateway:8000/storage/v1/
    ProxyPassReverse /storage/v1/ http://supabase-gateway:8000/storage/v1/
    ProxyPass /realtime/v1/ http://supabase-gateway:8000/realtime/v1/ upgrade=websocket
    ProxyPassReverse /realtime/v1/ http://supabase-gateway:8000/realtime/v1/
    ProxyPass /graphql/v1/ http://supabase-gateway:8000/graphql/v1/
    ProxyPassReverse /graphql/v1/ http://supabase-gateway:8000/graphql/v1/
    ProxyPass / http://frontend:3000/
    ProxyPassReverse / http://frontend:3000/
</VirtualHost>
