apiVersion: v1
kind: Service
metadata:
  name: v3-aggregator
  namespace: snapflow-prod
  labels:
    app: v3-aggregator
spec:
  type: NodePort
  selector:
    app: v3-aggregator
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
